apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-shared-platform-egress
  namespace: customer-digital
spec:
  podSelector:
    matchLabels:
      platform.mayabank.example/shared-egress-client: "true"
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: keycloak-system
      ports:
        - protocol: TCP
          port: 8080
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: shared-observability
      ports:
        - protocol: TCP
          port: 4318
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: mayabank-api
      ports:
        - protocol: TCP
          port: 8000
